#!/usr/bin/env python3
"""
submit.py  —  FCC ALLEGRO batch workflow orchestrator

Usage:
    # Generate DAG + all job files, then submit
    python batch/submit.py --config batch/config.yaml --steps gen sim reco merge ntuple

    # Dry-run: generate files only, do not submit
    python batch/submit.py --config batch/config.yaml --steps sim reco --dry-run

    # Generate the environment setup/compile script (run once before first submission)
    python batch/submit.py --config batch/config.yaml --setup

Available steps (can be any subset, chained in this fixed order):
    gen   — Pythia8 event generation
    sim   — ddsim full simulation
    reco  — k4run PandoraPFA reconstruction
    merge — hadd reco files
    ntuple— CaloNtupleizer
"""

import argparse
import math
import os
import stat
import sys
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
STEP_ORDER = ["gen", "sim", "reco", "merge", "ntuple"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_config(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def render(env: Environment, template_name: str, **kwargs) -> str:
    return env.get_template(template_name).render(**kwargs)


def write_executable(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def sample_tag(sample_name: str, ecm: float) -> str:
    """Unique tag for a (sample, ecm) combination, e.g. ttbar_ecm365."""
    ecm_str = f"{ecm:.3f}".rstrip("0").rstrip(".")
    return f"{sample_name}_ecm{ecm_str}"


def key4hep_flag(key4hep_setup: str) -> str:
    """Return the Key4hep setup string used in templates."""
    if key4hep_setup == "latest":
        return "latest"
    # strip the leading path so the template just gets the date string
    return key4hep_setup


# ---------------------------------------------------------------------------
# Setup / compile script generation
# ---------------------------------------------------------------------------

def generate_setup_script(cfg: dict, submitdir: Path) -> None:
    """Write a one-time setup_and_compile.sh from the packages config."""
    workdir = cfg["paths"]["workdir"]
    k4hep = cfg["paths"]["key4hep_setup"]
    packages = cfg.get("packages", {})

    k4hep_source = (
        "source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh"
        if k4hep == "latest"
        else f"source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh -r {k4hep}"
    )

    lines = [
        "#!/bin/bash",
        "# Auto-generated by submit.py --setup",
        "# Run this ONCE to clone and compile all dependencies.",
        "# Usage: bash batch/setup_and_compile.sh",
        "set -euo pipefail",
        "",
        f"export WORKDIR={workdir}",
        f"cd ${{WORKDIR}}",
        "",
        "# --- Key4hep environment ---",
        k4hep_source,
        "",
        "# PandoraCMakeSettings (not in latest nightly)",
        "export PANDORA_CMAKE_MODULE_PATH=/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2026-02-26/"
        "x86_64-almalinux9-gcc14.2.0-opt/pandorapfa/4.11.2-tyvaev/cmakemodules",
        "",
    ]

    # Clone / pull packages
    cmake_packages = ["PandoraSDK", "k4geo", "k4RecTracker", "LCContent",
                      "DDMarlinPandora", "CaloNtupleizer", "ALLEGRO_PandoraPFA"]
    pythia_pkg = "Pythia8"

    lines.append("# --- Clone or update repositories ---")
    for pkg_name, pkg_cfg in packages.items():
        if "local_path" in pkg_cfg:
            lines.append(f"# {pkg_name}: using local path {pkg_cfg['local_path']} (skipping clone)")
            continue
        git = pkg_cfg["git"]
        url = git["url"]
        branch = git["branch"]
        lines += [
            f"if [ ! -d ${{WORKDIR}}/{pkg_name} ]; then",
            f"  git clone {url} ${{WORKDIR}}/{pkg_name}",
            f"fi",
            f"cd ${{WORKDIR}}/{pkg_name} && git checkout {branch} && git pull && cd ${{WORKDIR}}",
            "",
        ]

    lines.append("# --- Compile cmake-based packages ---")
    pandora_flag = "-DCMAKE_MODULE_PATH=${PANDORA_CMAKE_MODULE_PATH}"
    for pkg in cmake_packages:
        if pkg not in packages:
            continue
        pkg_cfg = packages[pkg]
        if "local_path" in pkg_cfg:
            lines.append(f"# {pkg}: using local path, skipping compile")
            continue
        extra = pandora_flag if pkg in ("PandoraSDK", "LCContent", "DDMarlinPandora") else ""
        lines += [
            f"cd ${{WORKDIR}}/{pkg}",
            f"rm -rf build install && mkdir build install",
            f"cd build",
            f"cmake .. -DCMAKE_INSTALL_PREFIX=../install {extra}".strip(),
            f"make install -j$(nproc)",
            f"cd ..",
            f"k4_local_repo",
            f"cd ${{WORKDIR}}",
            "",
        ]

    lines.append("# --- Compile Pythia8 (standalone C++) ---")
    if pythia_pkg in packages and "local_path" not in packages[pythia_pkg]:
        hepmc3 = ("/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2026-02-26/"
                  "x86_64-almalinux9-gcc14.2.0-opt/hepmc3/3.3.1-3o4ayl/")
        lines += [
            f"cd ${{WORKDIR}}/{pythia_pkg}",
            f"export HEPMC3={hepmc3}",
            "export LD_LIBRARY_PATH=$PYTHIA8/lib:$LD_LIBRARY_PATH",
            "export LD_LIBRARY_PATH=$HEPMC3/lib64:$LD_LIBRARY_PATH",
            "mkdir -p bin",
            "c++ -O2 -std=c++20 main.cc \\",
            "  -I$PYTHIA8/include -I$HEPMC3/include \\",
            "  -L$PYTHIA8/lib -L$HEPMC3/lib64 \\",
            "  -Wl,-rpath,$PYTHIA8/lib:$HEPMC3/lib64 \\",
            "  -lpythia8 -lHepMC3 -ldl \\",
            "  -o bin/pythia",
            f"cd ${{WORKDIR}}",
            "",
        ]

    lines += [
        "# --- Copy large map files (if not already present) ---",
        "ARCHIL=/afs/cern.ch/work/a/adurglis/public/PandoraPFA/run",
        "RUNDIR=${WORKDIR}/ALLEGRO_PandoraPFA/run",
        "for f in neighbours_map_ecalB_hcalB_hcalE.root \\",
        "         neighbours_map_ecalE_turbine.root \\",
        "         cellNoise_map_electronicsNoiseLevel_ecalB_hcalB_hcalE.root; do",
        '  [ -f "${RUNDIR}/${f}" ] || cp "${ARCHIL}/${f}" "${RUNDIR}/"',
        "done",
        "",
        "echo 'Setup and compile complete.'",
    ]

    out = submitdir / "setup_and_compile.sh"
    write_executable(out, "\n".join(lines) + "\n")
    print(f"[setup] Written: {out}")
    print("[setup] WARNING: run  bash batch/setup_and_compile.sh  before submitting any jobs.")


# ---------------------------------------------------------------------------
# Per-step job generation
# ---------------------------------------------------------------------------

def make_gen_jobs(sample: dict, ecm: float, cfg: dict,
                  submitdir: Path, jinja_env: Environment) -> list[dict]:
    """Return list of DAG node dicts for generation jobs."""
    paths = cfg["paths"]
    wf = cfg["workflow"]["gen"]
    tag = sample_tag(sample["name"], ecm)
    nevents_total = sample["total_events"]
    nevents_job = wf["events_per_job"]
    n_jobs = math.ceil(nevents_total / nevents_job)
    base_seed = sample["base_seed"]

    nodes = []
    for i in range(n_jobs):
        job_name = f"gen_{tag}_{i:04d}"
        seed = base_seed + i
        output_dir = f"{paths['runsdir']}/gen/{tag}"
        output_file = f"gen_{tag}_{i:04d}"  # .hepmc appended by pythia

        script_content = render(
            jinja_env, "gen.sh.j2",
            sample_name=sample["name"], ecm=ecm, job_index=i,
            workdir=paths["workdir"], card=sample["card"],
            output_dir=output_dir, output_file=output_file,
            nevents=nevents_job, seed=seed,
            key4hep_setup=paths["key4hep_setup"],
        )
        script_path = submitdir / "scripts" / f"{job_name}.sh"
        write_executable(script_path, script_content)

        log_dir = submitdir / "logs" / tag
        log_dir.mkdir(parents=True, exist_ok=True)

        sub_content = render(
            jinja_env, "condor.sub.j2",
            job_name=job_name, script=script_path,
            log_dir=log_dir, job_flavour=wf["job_flavour"],
        )
        sub_path = submitdir / "condor" / f"{job_name}.sub"
        write_file(sub_path, sub_content)

        nodes.append({
            "name": job_name,
            "sub": sub_path,
            "step": "gen",
            "output_hepmc": f"{output_dir}/{output_file}.hepmc",
            "parents": [],
        })
    return nodes


def make_sim_jobs(sample: dict, ecm: float, cfg: dict,
                  submitdir: Path, jinja_env: Environment,
                  gen_nodes: list[dict]) -> list[dict]:
    """Return DAG node dicts for simulation jobs.
    Each gen job produces one HepMC file; sim jobs slice into it.
    """
    paths = cfg["paths"]
    wf_sim = cfg["workflow"]["sim"]
    wf_gen = cfg["workflow"]["gen"]
    tag = sample_tag(sample["name"], ecm)
    base_seed = sample["base_seed"]

    nodes = []
    sim_index = 0
    for gen_node in gen_nodes:
        hepmc_file = gen_node["output_hepmc"]
        nevents_in_file = wf_gen["events_per_job"]
        nevents_sim = wf_sim["events_per_job"]
        n_sim_per_gen = math.ceil(nevents_in_file / nevents_sim)

        for j in range(n_sim_per_gen):
            job_name = f"sim_{tag}_{sim_index:04d}"
            skip = j * nevents_sim
            seed = base_seed + 10000 + sim_index   # offset to avoid collision with gen seeds
            output_dir = f"{paths['runsdir']}/sim/{tag}"
            output_file = f"sim_{tag}_{sim_index:04d}.root"

            script_content = render(
                jinja_env, "sim.sh.j2",
                sample_name=sample["name"], ecm=ecm, job_index=sim_index,
                workdir=paths["workdir"],
                hepmc_file=hepmc_file,
                output_dir=output_dir, output_file=output_file,
                nevents=nevents_sim, skip_events=skip, seed=seed,
                key4hep_setup=paths["key4hep_setup"],
            )
            script_path = submitdir / "scripts" / f"{job_name}.sh"
            write_executable(script_path, script_content)

            log_dir = submitdir / "logs" / tag
            log_dir.mkdir(parents=True, exist_ok=True)

            sub_content = render(
                jinja_env, "condor.sub.j2",
                job_name=job_name, script=script_path,
                log_dir=log_dir, job_flavour=wf_sim["job_flavour"],
            )
            sub_path = submitdir / "condor" / f"{job_name}.sub"
            write_file(sub_path, sub_content)

            nodes.append({
                "name": job_name,
                "sub": sub_path,
                "step": "sim",
                "output_root": f"{output_dir}/{output_file}",
                "parents": [gen_node["name"]],
            })
            sim_index += 1
    return nodes


def make_reco_jobs(sample: dict, ecm: float, cfg: dict,
                   submitdir: Path, jinja_env: Environment,
                   sim_nodes: list[dict]) -> list[dict]:
    paths = cfg["paths"]
    wf = cfg["workflow"]["reco"]
    tag = sample_tag(sample["name"], ecm)
    base_seed = sample["base_seed"]

    nodes = []
    for i, sim_node in enumerate(sim_nodes):
        job_name = f"reco_{tag}_{i:04d}"
        output_dir = f"{paths['runsdir']}/reco/{tag}"
        output_file = f"reco_{tag}_{i:04d}.root"

        script_content = render(
            jinja_env, "reco.sh.j2",
            sample_name=sample["name"], ecm=ecm, job_index=i,
            workdir=paths["workdir"],
            sim_file=sim_node["output_root"],
            output_dir=output_dir, output_file=output_file,
            rundir=f"{paths['workdir']}/ALLEGRO_PandoraPFA/run",
            pandora_settings=cfg["paths"]["pandora_settings"],
            key4hep_setup=paths["key4hep_setup"],
        )
        script_path = submitdir / "scripts" / f"{job_name}.sh"
        write_executable(script_path, script_content)

        log_dir = submitdir / "logs" / tag
        log_dir.mkdir(parents=True, exist_ok=True)

        sub_content = render(
            jinja_env, "condor.sub.j2",
            job_name=job_name, script=script_path,
            log_dir=log_dir, job_flavour=wf["job_flavour"],
        )
        sub_path = submitdir / "condor" / f"{job_name}.sub"
        write_file(sub_path, sub_content)

        nodes.append({
            "name": job_name,
            "sub": sub_path,
            "step": "reco",
            "output_root": f"{output_dir}/{output_file}",
            "parents": [sim_node["name"]],
        })
    return nodes


def make_merge_jobs(sample: dict, ecm: float, cfg: dict,
                    submitdir: Path, jinja_env: Environment,
                    reco_nodes: list[dict]) -> list[dict]:
    """Merge reco files in chunks of `events_per_merged_file`.
    Since each reco job produces `events_per_job` events, we group accordingly.
    """
    paths = cfg["paths"]
    wf = cfg["workflow"]["merge"]
    wf_reco = cfg["workflow"]["reco"]
    tag = sample_tag(sample["name"], ecm)

    reco_per_merge = max(1, wf["events_per_merged_file"] // wf_reco["events_per_job"])
    chunks = [reco_nodes[i:i + reco_per_merge]
              for i in range(0, len(reco_nodes), reco_per_merge)]

    nodes = []
    for i, chunk in enumerate(chunks):
        job_name = f"merge_{tag}_{i:04d}"
        output_dir = f"{paths['runsdir']}/merge/{tag}"
        output_file = f"merge_{tag}_{i:04d}.root"
        input_files = [n["output_root"] for n in chunk]

        script_content = render(
            jinja_env, "merge.sh.j2",
            sample_name=sample["name"], ecm=ecm,
            output_dir=output_dir, output_file=output_file,
            input_files=input_files,
            key4hep_setup=paths["key4hep_setup"],
        )
        script_path = submitdir / "scripts" / f"{job_name}.sh"
        write_executable(script_path, script_content)

        log_dir = submitdir / "logs" / tag
        log_dir.mkdir(parents=True, exist_ok=True)

        sub_content = render(
            jinja_env, "condor.sub.j2",
            job_name=job_name, script=script_path,
            log_dir=log_dir, job_flavour=wf["job_flavour"],
        )
        sub_path = submitdir / "condor" / f"{job_name}.sub"
        write_file(sub_path, sub_content)

        nodes.append({
            "name": job_name,
            "sub": sub_path,
            "step": "merge",
            "output_root": f"{output_dir}/{output_file}",
            "parents": [n["name"] for n in chunk],
        })
    return nodes


def make_ntuple_job(sample: dict, ecm: float, cfg: dict,
                    submitdir: Path, jinja_env: Environment,
                    merge_nodes: list[dict]) -> dict:
    paths = cfg["paths"]
    wf = cfg["workflow"]["ntuple"]
    tag = sample_tag(sample["name"], ecm)

    job_name = f"ntuple_{tag}"
    output_dir = f"{paths['runsdir']}/ntuple/{tag}"
    output_file = f"ntuple_{tag}.root"
    input_files = [n["output_root"] for n in merge_nodes]

    script_content = render(
        jinja_env, "ntuple.sh.j2",
        sample_name=sample["name"], ecm=ecm,
        workdir=paths["workdir"],
        output_dir=output_dir, output_file=output_file,
        input_files=input_files,
        key4hep_setup=paths["key4hep_setup"],
    )
    script_path = submitdir / "scripts" / f"{job_name}.sh"
    write_executable(script_path, script_content)

    log_dir = submitdir / "logs" / tag
    log_dir.mkdir(parents=True, exist_ok=True)

    sub_content = render(
        jinja_env, "condor.sub.j2",
        job_name=job_name, script=script_path,
        log_dir=log_dir, job_flavour=wf["job_flavour"],
    )
    sub_path = submitdir / "condor" / f"{job_name}.sub"
    write_file(sub_path, sub_content)

    return {
        "name": job_name,
        "sub": sub_path,
        "step": "ntuple",
        "output_root": f"{output_dir}/{output_file}",
        "parents": [n["name"] for n in merge_nodes],
    }


# ---------------------------------------------------------------------------
# DAG generation
# ---------------------------------------------------------------------------

def write_dag(nodes: list[dict], dag_path: Path) -> None:
    """Write a DAGMan .dag file from a flat list of nodes with parent lists."""
    lines = ["# Auto-generated DAGMan file", ""]
    for node in nodes:
        lines.append(f"JOB {node['name']} {node['sub']}")
    lines.append("")
    for node in nodes:
        if node["parents"]:
            parents_str = " ".join(node["parents"])
            lines.append(f"PARENT {parents_str} CHILD {node['name']}")
    write_file(dag_path, "\n".join(lines) + "\n")
    print(f"[dag] Written: {dag_path}")


# ---------------------------------------------------------------------------
# Main workflow builder
# ---------------------------------------------------------------------------

def build_workflow(cfg: dict, steps: list[str],
                   submitdir: Path, jinja_env: Environment) -> list[Path]:
    """Build all job scripts and DAG files. Return list of DAG paths."""
    dag_paths = []

    for sample in cfg["samples"]:
        for ecm in sample["ecm"]:
            tag = sample_tag(sample["name"], ecm)
            all_nodes: list[dict] = []

            # We always build from scratch for each (sample, ecm) but only
            # include nodes for the requested steps. Dependencies between
            # steps are expressed via "phantom" parent names so DAGMan can
            # chain them even when intermediate steps were run previously.
            # If an upstream step is NOT in `steps`, its nodes are omitted
            # from the DAG — the user is responsible for ensuring the files
            # already exist.

            gen_nodes = sim_nodes = reco_nodes = merge_nodes = []

            if "gen" in steps and cfg["workflow"]["gen"]["enabled"]:
                gen_nodes = make_gen_jobs(sample, ecm, cfg, submitdir, jinja_env)
                all_nodes.extend(gen_nodes)

            if "sim" in steps and cfg["workflow"]["sim"]["enabled"]:
                # If gen not in this DAG, build placeholder parent list from
                # expected output filenames only (no DAG dependency).
                if not gen_nodes:
                    # Reconstruct expected HepMC paths without creating DAG nodes
                    wf_gen = cfg["workflow"]["gen"]
                    n_gen = math.ceil(sample["total_events"] / wf_gen["events_per_job"])
                    runsdir = cfg["paths"]["runsdir"]
                    gen_nodes = [
                        {
                            "name": None,
                            "output_hepmc": (
                                f"{runsdir}/gen/{tag}/gen_{tag}_{i:04d}.hepmc"
                            ),
                        }
                        for i in range(n_gen)
                    ]
                sim_nodes = make_sim_jobs(sample, ecm, cfg, submitdir, jinja_env, gen_nodes)
                # strip phantom parents so DAG edges only reference real nodes
                for n in sim_nodes:
                    n["parents"] = [p for p in n["parents"] if p is not None]
                all_nodes.extend(sim_nodes)

            if "reco" in steps and cfg["workflow"]["reco"]["enabled"]:
                if not sim_nodes:
                    wf_gen = cfg["workflow"]["gen"]
                    wf_sim = cfg["workflow"]["sim"]
                    n_gen = math.ceil(sample["total_events"] / wf_gen["events_per_job"])
                    n_sim = n_gen * math.ceil(wf_gen["events_per_job"] / wf_sim["events_per_job"])
                    runsdir = cfg["paths"]["runsdir"]
                    sim_nodes = [
                        {
                            "name": None,
                            "output_root": f"{runsdir}/sim/{tag}/sim_{tag}_{i:04d}.root",
                        }
                        for i in range(n_sim)
                    ]
                reco_nodes = make_reco_jobs(sample, ecm, cfg, submitdir, jinja_env, sim_nodes)
                for n in reco_nodes:
                    n["parents"] = [p for p in n["parents"] if p is not None]
                all_nodes.extend(reco_nodes)

            if "merge" in steps and cfg["workflow"]["merge"]["enabled"]:
                if not reco_nodes:
                    wf_gen = cfg["workflow"]["gen"]
                    wf_sim = cfg["workflow"]["sim"]
                    n_gen = math.ceil(sample["total_events"] / wf_gen["events_per_job"])
                    n_sim = n_gen * math.ceil(wf_gen["events_per_job"] / wf_sim["events_per_job"])
                    runsdir = cfg["paths"]["runsdir"]
                    reco_nodes = [
                        {
                            "name": None,
                            "output_root": f"{runsdir}/reco/{tag}/reco_{tag}_{i:04d}.root",
                        }
                        for i in range(n_sim)
                    ]
                merge_nodes = make_merge_jobs(sample, ecm, cfg, submitdir, jinja_env, reco_nodes)
                for n in merge_nodes:
                    n["parents"] = [p for p in n["parents"] if p is not None]
                all_nodes.extend(merge_nodes)

            if "ntuple" in steps and cfg["workflow"]["ntuple"]["enabled"]:
                if not merge_nodes:
                    wf_gen = cfg["workflow"]["gen"]
                    wf_sim = cfg["workflow"]["sim"]
                    wf_merge = cfg["workflow"]["merge"]
                    wf_reco = cfg["workflow"]["reco"]
                    n_gen = math.ceil(sample["total_events"] / wf_gen["events_per_job"])
                    n_sim = n_gen * math.ceil(wf_gen["events_per_job"] / wf_sim["events_per_job"])
                    reco_per_merge = max(1, wf_merge["events_per_merged_file"] // wf_reco["events_per_job"])
                    n_merge = math.ceil(n_sim / reco_per_merge)
                    runsdir = cfg["paths"]["runsdir"]
                    merge_nodes = [
                        {
                            "name": None,
                            "output_root": f"{runsdir}/merge/{tag}/merge_{tag}_{i:04d}.root",
                        }
                        for i in range(n_merge)
                    ]
                ntuple_node = make_ntuple_job(sample, ecm, cfg, submitdir, jinja_env, merge_nodes)
                ntuple_node["parents"] = [p for p in ntuple_node["parents"] if p is not None]
                all_nodes.append(ntuple_node)

            if not all_nodes:
                print(f"[{tag}] No enabled steps — skipping.")
                continue

            dag_path = submitdir / "dags" / f"{tag}.dag"
            write_dag(all_nodes, dag_path)
            dag_paths.append(dag_path)
            n_jobs = len(all_nodes)
            steps_in_dag = sorted({n["step"] for n in all_nodes}, key=STEP_ORDER.index)
            print(f"[{tag}] DAG with {n_jobs} jobs, steps: {' -> '.join(steps_in_dag)}")

    return dag_paths


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--config", required=True, help="Path to config.yaml")
    parser.add_argument("--steps", nargs="+", choices=STEP_ORDER, metavar="STEP",
                        help="Steps to include (gen sim reco merge ntuple). "
                             "Multiple steps are chained via DAGMan.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Generate job files but do not submit to HTCondor.")
    parser.add_argument("--setup", action="store_true",
                        help="Generate setup_and_compile.sh and exit.")
    args = parser.parse_args()

    cfg = load_config(args.config)
    submitdir = Path(cfg["paths"]["submitdir"])
    submitdir.mkdir(parents=True, exist_ok=True)

    # Locate templates relative to this script
    script_dir = Path(__file__).parent
    jinja_env = Environment(loader=FileSystemLoader(str(script_dir / "templates")),
                            keep_trailing_newline=True)

    if args.setup:
        generate_setup_script(cfg, submitdir)
        return

    if not args.steps:
        parser.error("--steps is required unless --setup is given.")

    # Enforce canonical order
    steps = [s for s in STEP_ORDER if s in args.steps]

    dag_paths = build_workflow(cfg, steps, submitdir, jinja_env)

    if not dag_paths:
        print("No DAGs generated.")
        return

    if args.dry_run:
        print(f"\n[dry-run] {len(dag_paths)} DAG(s) written. Not submitting.")
        for p in dag_paths:
            print(f"  {p}")
        return

    print(f"\nSubmitting {len(dag_paths)} DAG(s)...")
    import subprocess
    for dag in dag_paths:
        result = subprocess.run(["condor_submit_dag", str(dag)],
                                capture_output=True, text=True)
        if result.returncode == 0:
            print(f"  [OK] {dag.name}")
        else:
            print(f"  [FAIL] {dag.name}")
            print(result.stderr)


if __name__ == "__main__":
    main()
