#!/usr/bin/env python

import os, sys, glob, argparse
from datetime import date
import ROOT
print ("Load cxx analyzers ... ")
ROOT.gSystem.Load("libCaloNtupleizer.so")
ROOT.gErrorIgnoreLevel = ROOT.kFatal

def str2bool(v):
    if isinstance(v, bool):
        return v
    if v.lower() in ('yes', 'true', 't', 'y', '1'):
        return True
    elif v.lower() in ('no', 'false', 'f', 'n', '0'):
        return False
    else:
        raise argparse.ArgumentTypeError('Boolean value expected.')


parser = argparse.ArgumentParser(description='Create calo ntuple')

parser.add_argument(
    '--inputFiles',
    nargs='+',type=str, default=['ALLEGRO_sim_digi_reco.root'],
    help='Input rootfiles (can be a single file or a regex)')
parser.add_argument('--outputFile',
    type=str, default = 'caloNtuple.root',
    help = 'Output rootfile name')
parser.add_argument('--outputDir',
    type=str, default = './',
    help = 'Output directory for the rootfiles')
parser.add_argument(
    '--storeCellBranches',
    type=str2bool, default=True,
    help='Whether or not to store cell information')
parser.add_argument(
    '--cellBranchNames',
    nargs='+', default=['HCalBarrelReadoutPositioned','HCalEndcapReadoutPositioned','ECalBarrelModuleThetaMergedPositioned'],
    help='Names of the cell branches in the input rootfile. Must have position information!')
parser.add_argument(
    '--storeClusterBranches',
    type=str2bool, default=False,
    help='Whether or not to store cluster information')
parser.add_argument(
    '--clusterBranchNames',
    nargs='+', default=['CaloTopoClusters'],
    help='Name of the cluster branch in the input rootfile')
parser.add_argument(
    '--storePfoBranches',
    type=str2bool, default=True,
    help='Whether or not to store PFO information')
parser.add_argument(
    '--pfoBranchNames',
    nargs='+', default=['PandoraPFANewPFOs'],
    help='Name of the PFO branch in the input rootfile')
parser.add_argument(
    '--storeClusterCellsBranches',
    type=str2bool, default=False,
    help='Whether or not to store cluster cells information')
parser.add_argument(
    '--clusterCellsBranchNames',
    nargs='+', default=['CaloTopoClusterCells'],
    help='Name of the cluster-attached-cells branches in the input rootfile. Order must follow --clusterBranchNames and the cells must have positions attached!')
parser.add_argument(
    '--storeGenBranches',
    type=str2bool, default=True,
    help='Whether or not to store gen information')
parser.add_argument(
    '--genBranchName',
    type=str, default='MCParticles',
    help='Name of the gen particle branch in the input rootfile')
parser.add_argument(
    '--storeSimParticleSecondaries',
    type=str2bool, default=False,
    help='Whether to store the SimParticleSecondaries information')
parser.add_argument(
    '--simParticleSecondariesNames',
    nargs='+', default=['SimParticleSecondaries'],
    help='name of the SimParticleSecondaries branch')
parser.add_argument(
    '--useGeometry',
    type=str2bool, default=True,
    help='Whether or not to load the FCCSW geometry. Used to get the detector segmentation for e.g. the definition of the cell layer index.')
parser.add_argument(
    '-geometryFile',
    type=str, default=os.environ['K4GEO'] + '/FCCee/ALLEGRO/compact/ALLEGRO_o1_v03/ALLEGRO_o1_v03.xml',
    help='Path to the xml geometry file')
parser.add_argument(
    '--readoutName',
    nargs='+', default=['HCalBarrelReadout','HCalEndcapReadout','ECalBarrelModuleThetaMerged'],
    help='Name of the readout to use for the layer/phi/theta bin definition')

args = parser.parse_args()
##################################################################

class analysis():

    def __init__(self, inputlist, outname, ncpu):
        self.outname = outname
        if ".root" not in outname:
            self.outname+=".root"

        ROOT.ROOT.EnableImplicitMT(ncpu)
        ROOT.gInterpreter.Declare("using namespace FCCAnalyses;")

        self.df = ROOT.RDataFrame("events", inputlist)
        if args.useGeometry:
            readoutList = ROOT.vector('string')()
            for readout in args.readoutName: readoutList.push_back(readout)
            ROOT.CaloNtupleizer.PyInterface.loadGeometry(args.geometryFile, readoutList)

    def run(self):

        dict_outputBranchName_function = {}
        # event number
        dict_outputBranchName_function["EventHeader_eventNumber"] = "EventHeader.eventNumber"

        # cells
        if args.storeCellBranches:
            for cellBranchName in args.cellBranchNames:
                dict_outputBranchName_function["%s_x"%cellBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_x(%s)"%cellBranchName
                dict_outputBranchName_function["%s_y"%cellBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_y(%s)"%cellBranchName
                dict_outputBranchName_function["%s_z"%cellBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_z(%s)"%cellBranchName
                dict_outputBranchName_function["%s_phi"%cellBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_phi(%s)"%cellBranchName
                dict_outputBranchName_function["%s_theta"%cellBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_theta(%s)"%cellBranchName
                dict_outputBranchName_function["%s_energy"%cellBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_energy(%s)"%cellBranchName
                dict_outputBranchName_function["%s_totalEnergy"%cellBranchName] = "CaloNtupleizer::PyInterface::getTotalCalo_energy(%s)"%cellBranchName
                if args.useGeometry:
                  if 'ECal' in cellBranchName:
                    dict_outputBranchName_function["%s_moduleIdx"%cellBranchName] = 'CaloNtupleizer::PyInterface::getCaloHit_moduleIdx(%s,"%s")'%(cellBranchName,cellBranchName.removesuffix("Positioned"))
                    dict_outputBranchName_function["%s_thetaIdx"%cellBranchName] = 'CaloNtupleizer::PyInterface::getCaloHit_thetaIdx(%s,"%s")'%(cellBranchName,cellBranchName.removesuffix("Positioned"))
                  dict_outputBranchName_function["%s_layer"%cellBranchName] = 'CaloNtupleizer::PyInterface::getCaloHit_layer(%s,"%s")'%(cellBranchName,cellBranchName.removesuffix("Positioned"))
                  dict_outputBranchName_function["%s_layerEnergy"%cellBranchName] = 'CaloNtupleizer::PyInterface::getCaloLayer_energy(%s,"%s")'%(cellBranchName,cellBranchName.removesuffix("Positioned"))
#                  if 'HCalEndcap' in cellBranchName:
#                    dict_outputBranchName_function["%s_pseudoLayerEnergy"%cellBranchName] = 'CaloNtupleizer::PyInterface::getCaloPseudoLayer_energy(%s,"%s")'%(cellBranchName,cellBranchName.removesuffix("Positioned"))
#                    dict_outputBranchName_function["%s_pseudoLayer"%cellBranchName] = 'CaloNtupleizer::PyInterface::getCaloHit_pseudoLayer(%s,"%s")'%(cellBranchName,cellBranchName.removesuffix("Positioned"))

        # clusters
        if args.storeClusterBranches:
            for clusterBranchName in args.clusterBranchNames:
                dict_outputBranchName_function["%s_x"%clusterBranchName] = "CaloNtupleizer::PyInterface::getCaloCluster_x(%s)"%clusterBranchName
                dict_outputBranchName_function["%s_y"%clusterBranchName] = "CaloNtupleizer::PyInterface::getCaloCluster_y(%s)"%clusterBranchName
                dict_outputBranchName_function["%s_z"%clusterBranchName] = "CaloNtupleizer::PyInterface::getCaloCluster_z(%s)"%clusterBranchName
                dict_outputBranchName_function["%s_phi"%clusterBranchName] = "CaloNtupleizer::PyInterface::getCaloCluster_phi(%s)"%clusterBranchName
                dict_outputBranchName_function["%s_theta"%clusterBranchName] = "CaloNtupleizer::PyInterface::getCaloCluster_theta(%s)"%clusterBranchName
                dict_outputBranchName_function["%s_eta"%clusterBranchName] = "CaloNtupleizer::PyInterface::getCaloCluster_eta(%s)"%clusterBranchName
                dict_outputBranchName_function["%s_energy"%clusterBranchName] = "CaloNtupleizer::PyInterface::getCaloCluster_energy(%s)"%clusterBranchName
                dict_outputBranchName_function["%s_firstCell"%clusterBranchName] = "CaloNtupleizer::PyInterface::getCaloCluster_firstCell(%s)"%clusterBranchName
                dict_outputBranchName_function["%s_lastCell"%clusterBranchName] = "CaloNtupleizer::PyInterface::getCaloCluster_lastCell(%s)"%clusterBranchName

        # cells attached to clusters
        if args.storeClusterCellsBranches:
            for clusterCellsBranchName in args.clusterCellsBranchNames:
                dict_outputBranchName_function["%s_x"%clusterCellsBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_x(%s)"%clusterCellsBranchName
                dict_outputBranchName_function["%s_y"%clusterCellsBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_y(%s)"%clusterCellsBranchName
                dict_outputBranchName_function["%s_z"%clusterCellsBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_z(%s)"%clusterCellsBranchName
                dict_outputBranchName_function["%s_phi"%clusterCellsBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_phi(%s)"%clusterCellsBranchName
                dict_outputBranchName_function["%s_theta"%clusterCellsBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_theta(%s)"%clusterCellsBranchName
                dict_outputBranchName_function["%s_energy"%clusterCellsBranchName] = "CaloNtupleizer::PyInterface::getCaloHit_energy(%s)"%clusterCellsBranchName
                if args.useGeometry:
                  if 'ECal' in clusterCellsBranchName:
                    dict_outputBranchName_function["%s_moduleIdx"%clusterCellsBranchName] = 'CaloNtupleizer::PyInterface::getCaloHit_moduleIdx(%s,"%s")'%(clusterCellsBranchName,clusterCellsBranchName.removesuffix("Positioned"))
                    dict_outputBranchName_function["%s_thetaIdx"%clusterCellsBranchName] = 'CaloNtupleizer::PyInterface::getCaloHit_thetaIdx(%s,"%s")'%(clusterCellsBranchName,clusterCellsBranchName.removesuffix("Positioned"))
                  dict_outputBranchName_function["%s_layer"%clusterCellsBranchName] = 'CaloNtupleizer::PyInterface::getCaloHit_layer(%s,"%s")'%(clusterCellsBranchName,clusterCellsBranchName.removesuffix("Positioned"))

        # PFOs
        if args.storePfoBranches:
            for pfoBranchName in args.pfoBranchNames:
                #dict_outputBranchName_function["%s_momentumVector3"%pfoBranchName] = "CaloNtupleizer::PyInterface::getPFO_momentumVector3(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_PDG"%pfoBranchName] = "CaloNtupleizer::PyInterface::getPFO_PDG(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_energy"%pfoBranchName] = "CaloNtupleizer::PyInterface::getPFO_energy(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_totalEnergy"%pfoBranchName] = "CaloNtupleizer::PyInterface::getTotalPFO_energy(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_neutralHadronEnergy"%pfoBranchName] = "CaloNtupleizer::PyInterface::getNeutralHadronPFO_energy(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_chargedHadronEnergy"%pfoBranchName] = "CaloNtupleizer::PyInterface::getChargedHadronPFO_energy(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_photonEnergy"%pfoBranchName] = "CaloNtupleizer::PyInterface::getPhotonPFO_energy(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_electronEnergy"%pfoBranchName] = "CaloNtupleizer::PyInterface::getElectronPFO_energy(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_number"%pfoBranchName] = "CaloNtupleizer::PyInterface::getPFO_number(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_neutralHadronNumber"%pfoBranchName] = "CaloNtupleizer::PyInterface::getNeutralHadronPFO_number(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_chargedHadronNumber"%pfoBranchName] = "CaloNtupleizer::PyInterface::getChargedHadronPFO_number(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_photonNumber"%pfoBranchName] = "CaloNtupleizer::PyInterface::getPhotonPFO_number(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_electronNumber"%pfoBranchName] = "CaloNtupleizer::PyInterface::getElectronPFO_number(%s)"%pfoBranchName
                dict_outputBranchName_function["%s_KlongPFO_dphi"%pfoBranchName] = "CaloNtupleizer::PyInterface::getKlongPFO_dphi(%s,%s)"%(pfoBranchName,args.genBranchName)
                dict_outputBranchName_function["%s_KlongPFO_dtheta"%pfoBranchName] = "CaloNtupleizer::PyInterface::getKlongPFO_dtheta(%s,%s)"%(pfoBranchName,args.genBranchName)
                dict_outputBranchName_function["%s_KlongPFO_dphi1"%pfoBranchName]  = "CaloNtupleizer::PyInterface::getKlongPFO_dphi1(%s,%s)"%(pfoBranchName,args.genBranchName)
                dict_outputBranchName_function["%s_KlongPFO_dtheta1"%pfoBranchName]  = "CaloNtupleizer::PyInterface::getKlongPFO_dtheta1(%s,%s)"%(pfoBranchName,args.genBranchName)

        # SimParticleSecondaries
        if args.storeSimParticleSecondaries:
            for SimParticleSecondariesName in args.simParticleSecondariesNames:
                dict_outputBranchName_function["%s_x"%SimParticleSecondariesName] = "CaloNtupleizer::PyInterface::getSimParticleSecondaries_x(%s)"%SimParticleSecondariesName
                dict_outputBranchName_function["%s_y"%SimParticleSecondariesName] = "CaloNtupleizer::PyInterface::getSimParticleSecondaries_y(%s)"%SimParticleSecondariesName
                dict_outputBranchName_function["%s_z"%SimParticleSecondariesName] = "CaloNtupleizer::PyInterface::getSimParticleSecondaries_z(%s)"%SimParticleSecondariesName
                dict_outputBranchName_function["%s_phi"%SimParticleSecondariesName] = "CaloNtupleizer::PyInterface::getSimParticleSecondaries_phi(%s)"%SimParticleSecondariesName
                dict_outputBranchName_function["%s_theta"%SimParticleSecondariesName] = "CaloNtupleizer::PyInterface::getSimParticleSecondaries_theta(%s)"%SimParticleSecondariesName
                dict_outputBranchName_function["%s_eta"%SimParticleSecondariesName] = "CaloNtupleizer::PyInterface::getSimParticleSecondaries_eta(%s)"%SimParticleSecondariesName
                dict_outputBranchName_function["%s_energy"%SimParticleSecondariesName] = "CaloNtupleizer::PyInterface::getSimParticleSecondaries_energy(%s)"%SimParticleSecondariesName
                dict_outputBranchName_function["%s_PDG"%SimParticleSecondariesName] = "CaloNtupleizer::PyInterface::getSimParticleSecondaries_PDG(%s)"%SimParticleSecondariesName

        # gen particles
        if args.storeGenBranches:
            dict_outputBranchName_function["genParticle_phi"] = "CaloNtupleizer::PyInterface::getMCParticle_phi(%s)"%args.genBranchName
            dict_outputBranchName_function["genParticle_theta"] = "CaloNtupleizer::PyInterface::getMCParticle_theta(%s)"%args.genBranchName
            dict_outputBranchName_function["genParticle_energy"] = "CaloNtupleizer::PyInterface::getMCParticle_energy(%s)"%args.genBranchName
            dict_outputBranchName_function["genParticle_pid"] = "CaloNtupleizer::PyInterface::getMCParticle_PDG(%s)"%args.genBranchName
            dict_outputBranchName_function["genParticle_status"] = "CaloNtupleizer::PyInterface::getMCParticle_status(%s)"%args.genBranchName
            dict_outputBranchName_function["genParticle_cosThetaQQ"] = "CaloNtupleizer::PyInterface::getQQ_cosTheta(%s)"%args.genBranchName
            dict_outputBranchName_function["genParticle_vertex_z"] = "CaloNtupleizer::PyInterface::getMCParticle_vertex_z(%s)"%args.genBranchName

        df2 = self.df
        branchList = ROOT.vector('string')()

        for branchName in dict_outputBranchName_function:
            df2 = df2.Define(branchName, dict_outputBranchName_function[branchName])
            if not "transient" in branchName:
                branchList.push_back(branchName)
                print(branchName, dict_outputBranchName_function[branchName])

        print('saving tree into', self.outname)
        df2.Snapshot("events", self.outname, branchList)
###############################################################


filelist = []
for file in args.inputFiles:
    if '*' in file:
       filelist += glob.glob(file)
    else:
       filelist.append(file)

if not filelist:
    print('No input found! Aborting...')
    sys.exit(3)

fileListRoot = ROOT.vector('string')()
print ("Input files:")
for fileName in filelist:
    fileListRoot.push_back(fileName)
    print ("\t", fileName)

if not os.path.exists(args.outputDir):
    os.makedirs(args.outputDir)

outputFile = args.outputDir + '/' + args.outputFile
ncpus = 10
analysis = analysis(fileListRoot, outputFile, ncpus)
print ("Processing...")
print('outputname = ',outputFile)
analysis.run()
print (os.path.join(os.environ.get("PWD"), outputFile), " written.")
